apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptr-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptr-ui
  template:
    metadata:
      labels:
        app: ptr-ui
    spec:
      containers:
        - name: ptr-ui
          image: mateusznowak/kub-ptr-ui:latest