INSERT INTO plan VALUES ('1', 'Basic');
INSERT INTO plan VALUES ('2', 'Pro');

INSERT INTO role VALUES (1, 'ROLE_BASIC');
INSERT INTO role VALUES (2, 'ROLE_PRO');
INSERT INTO role VALUES (3, 'ROLE_ADMIN');